# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_round', models.IntegerField()),
                ('pick_number', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(default=2015)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
            ],
            options={
                'ordering': ['year', 'selection_round', 'pick_number'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_key', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('league_name', models.CharField(blank=True, max_length=30, null=True)),
                ('num_teams', models.IntegerField()),
                ('num_roster_spots', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_key', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('manager_name', models.CharField(blank=True, max_length=30, null=True)),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
            ],
            options={
                'ordering': ['manager_name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_key', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=6)),
                ('nfl_team', models.CharField(max_length=3)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCost',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rosters.Player')),
                ('cost_2015', models.IntegerField(default=1)),
                ('cost_2016', models.IntegerField(default=1)),
                ('cost_2017', models.IntegerField(default=1)),
                ('cost_2018', models.IntegerField(default=1)),
                ('cost_2019', models.IntegerField(default=1)),
                ('drafted_year', models.IntegerField(blank=True, null=True)),
                ('rookie_status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update')),
            ],
            options={
                'ordering': ['player'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='manager',
            field=models.ForeignKey(default='FA', on_delete=django.db.models.deletion.CASCADE, to='rosters.Manager'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='current_owner',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_pick_owner', to='rosters.Manager'), on_delete=django.db.models.deletion.CASCADE, related_name='current_pick_owner', to='rosters.Manager'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='original_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_pick_owner', to='rosters.Manager'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rosters.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together=set([('original_owner', 'year', 'selection_round', 'pick_number')]),
        ),
    ]
